x = [1 5 2 8 9 0 1]; 
y = [5 2 2 6 0 0 2] ;
fprintf('(x > y)= ');
disp(x > y);
fprintf('(y < x)= ');
disp(y < x);
fprintf('(x==y)= ');
disp(x == y);
fprintf('(x<=y)= ');
disp(x <= y);
fprintf('(y>=x)= ');
disp(y >= x);
fprintf('(x | y)= ');
disp(x | y);
fprintf('(x&y)= ');
disp(x & y);
fprintf('(x&-y)= ');
disp(x & -y);
fprintf('(x>y) | (y<x) = ');
disp((x>y) | (y<x));
fprintf('(x>y) & (y<x)= ');
 disp((x>y) & (y<x));
